# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Function to compute one statistic at time
#' 
#' @param x Numeric Vector
#' @param y Numeric Vector
#' @param alpha alpha parameter for the mine statistic
#' @param C c parameter for the mine statistic
#' @param est estimation parameter for the mine statistic
#' @param measure character which measure to return
#' @param eps eps value for MCN statistic
#' @param p probability for the generalized mic
#' @param norm boolean if require normalization between 0 and 1 for the tic statistic
#' @export
mine_compute <- function(x, y, alpha = 0.6, C = 15, est = "mic_approx", measure = 1L, eps = 0.0, p = -1, norm = FALSE) {
    .Call('_minerva_mine_compute', PACKAGE = 'minerva', x, y, alpha, C, est, measure, eps, p, norm)
}

#' Function to compute mictools null distribution
#' 
#' @inheritParams mine_compute
#' @param nperm numper of permutation
#' @param seed character which measure to return
#' 
#' @export
mictools_null <- function(x, alpha = 9, C = 5, nperm = 250000L, seed = 0L) {
    .Call('_minerva_mictools_null', PACKAGE = 'minerva', x, alpha, C, nperm, seed)
}

#' Function to compute the pvalue for the mictools pipeline
#' 
#' @inheritParams mictools_null
#' @param est estimation parameter for the mine statistic
#' @export
mictools_pstats <- function(x, alpha = 0.6, C = 15L, est = "mic_approx") {
    .Call('_minerva_mictools_pstats', PACKAGE = 'minerva', x, alpha, C, est)
}

